name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'yarn'

    - run: npm pkg delete scripts.prepare

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Running Lint
      run: yarn ci:lint

    - name: Running Typecheck
      run: yarn typecheck

    - name: Running Tests
      run: yarn ci:test
